FROM alpine:latest


WORKDIR /home/app/config/



RUN \
apk -qq update ; \
apk -qq upgrade
###

RUN \
apk add -U \
  sudo \
  neofetch \
  curl \
  wget \
  htop \
  nano \
  ufw \
  rclone \
  iptables \
  wireguard-tools \
  nginx
###
